In [2]:
import numpy as np

In [3]:
np.random.rand(2,3)

array([[0.25167694, 0.9575007 , 0.23633584],
       [0.39055923, 0.93192563, 0.59658306]])

In [10]:
a = np.arange(18)
print(a)
a.reshape(9,2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [16]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr*arr)
print(arr+arr)
print(1/arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [30]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)

print(arr2d[:, 1]) #[2,5,8]
temp = np.zeros(3) #[1,5,9]
for i in range(len(arr2d)):
    temp[i] = arr2d[i, i]
print(temp)
print(arr2d[:2, 2])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]
[1. 5. 9.]
[3 6]


In [23]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
print(arr3d[:, :, 1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 2  5]
 [ 8 11]]


In [31]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)
print(names == 'Bob')
print(data[names == 'Bob'])


['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 1.23029473  0.17571504 -0.90731063  1.25119552]
 [ 0.82926415 -0.50687083 -0.57661562  1.15823678]
 [ 0.34460403 -0.0520647  -0.13406791 -1.94312777]
 [-0.2028678   1.57085298 -1.82193013 -0.10484745]
 [ 0.71133301 -0.47396061  0.63512487  2.32594868]
 [ 0.18278803  0.8812514  -0.25927516 -0.48649283]
 [-1.18269049  0.07191156  0.53600793 -0.02649776]]
[ True False False  True False False False]
[[ 1.23029473  0.17571504 -0.90731063  1.25119552]
 [-0.2028678   1.57085298 -1.82193013 -0.10484745]]


In [32]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [33]:
arr = np.arange(32).reshape((8, 4))
print(arr)
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])   # Here the elements (1, 0), (5, 3), (7, 1), and (2, 2) were selected.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 4 23 29 10]


In [34]:
arr = np.random.randn(6, 3)
print(arr)
print('----------------------------')
print(arr.T@arr)    # Matrix dot product

[[-0.4512338  -0.55487816 -0.89571034]
 [-1.35427116 -0.6343914   1.4840804 ]
 [-2.34675812  0.3626188   0.81858424]
 [ 1.03970997  0.20448282 -2.5814667 ]
 [ 1.60824704 -0.41850066  1.63059632]
 [ 0.87373211  0.18532888  0.73625742]]
----------------------------
[[11.97579919 -0.03998268 -2.94497494]
 [-0.03998268  1.09313745 -1.22146518]
 [-2.94497494 -1.22146518 13.5397615 ]]


In [44]:
print(arr3d)
arr3d.swapaxes(2, 1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[[ 1,  4],
        [ 2,  5],
        [ 3,  6]],

       [[ 7, 10],
        [ 8, 11],
        [ 9, 12]]])

In [45]:
x = np.random.randn(8)
y = np.random.randn(8)
print(x)
print(y)
print(np.maximum(x, y))   # calculate the point-wise maximum/

[-1.89894463 -1.69593345 -0.07288398  2.04153947 -1.48680731 -0.47732519
 -1.58256993  0.30688081]
[-0.61342077  0.86238499  0.71990224  0.43312911 -0.11927789 -0.16758718
  0.34937853 -0.53555254]
[-0.61342077  0.86238499  0.71990224  2.04153947 -0.11927789 -0.16758718
  0.34937853  0.30688081]


In [46]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points) #Takes 2 1d arrays and produce two 2D matrcies
print(xs)
print(ys)

[[-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 ...
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]]
[[-5.   -5.   -5.   ... -5.   -5.   -5.  ]
 [-4.99 -4.99 -4.99 ... -4.99 -4.99 -4.99]
 [-4.98 -4.98 -4.98 ... -4.98 -4.98 -4.98]
 ...
 [ 4.97  4.97  4.97 ...  4.97  4.97  4.97]
 [ 4.98  4.98  4.98 ...  4.98  4.98  4.98]
 [ 4.99  4.99  4.99 ...  4.99  4.99  4.99]]


In [49]:
arr = np.random.randn(5, 4)
print(arr)
print(arr > 0)
print(np.where(arr > 0, 9, -69))

[[-0.48437193  0.38770019 -1.61804935 -0.46581536]
 [ 1.63975011 -1.57085756 -1.05316995 -0.05353617]
 [ 0.06820946  0.15148132 -0.12473697  0.32620925]
 [ 1.08415334  1.56270064 -0.42885929 -0.38430252]
 [-0.62724418 -1.5683097  -0.83570624  0.39555957]]
[[False  True False False]
 [ True False False False]
 [ True  True False  True]
 [ True  True False False]
 [False False False  True]]
[[-69   9 -69 -69]
 [  9 -69 -69 -69]
 [  9   9 -69   9]
 [  9   9 -69 -69]
 [-69 -69 -69   9]]


In [51]:
print(arr.mean(axis=1))
print(arr.sum(axis=0))
print(arr.cumsum(axis = 0))

[-0.54513411 -0.25945339  0.10529076  0.45842304 -0.65892514]
[ 1.68049678 -1.03728511 -4.06052179 -0.18188523]
[[-0.48437193  0.38770019 -1.61804935 -0.46581536]
 [ 1.15537817 -1.18315737 -2.6712193  -0.51935153]
 [ 1.22358763 -1.03167605 -2.79595627 -0.19314228]
 [ 2.30774096  0.53102459 -3.22481555 -0.5774448 ]
 [ 1.68049678 -1.03728511 -4.06052179 -0.18188523]]


In [57]:
arr = np.random.randn(5)
a = sorted(arr)
print(arr)
print(a)
arr.sort()
print(arr)

[-0.30032822 -0.58883086  0.89533929 -0.76758898  0.41594212]
[-0.7675889765170127, -0.5888308641764681, -0.3003282211641344, 0.4159421231303476, 0.8953392940451377]
[-0.76758898 -0.58883086 -0.30032822  0.41594212  0.89533929]


In [64]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(ints))

['Bob' 'Joe' 'Will']
[1 2 3 4]


In [70]:
samples = np.random.normal(size = (3, 3))
samples

array([[-1.0949263 , -0.33229589, -1.21195353],
       [-0.03400852, -1.11656954,  0.05935712],
       [-0.75324744,  1.05551227,  0.2194765 ]])

In [85]:
np.random.seed(1234)
np.random.rand(5)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581])

In [84]:
np.random.seed(1234)
np.random.rand(5)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581])