In [2]:
import random,numpy as np, matplotlib as plt

In [26]:
def random_walk_simulations(nsteps, nwalks):
    """
    nsteps (int): the number of steps in each random walk process;
    nwalks (int): the number of random walks at once;
    Return three quantities:
    1. walks_max: ndarray with shape (nwalks,) that records the max value across nwalks random walk paths;
    2. walks_min: ndarray with shape (nwalks,) that records the min value across nwalks random walk paths;
    3. first_crossing_time: ndarray with shape (nwalks,) that records the first passing time across 
                            nwalks random walk paths.
    """
    draws = np.random.randint(0, 2, size=(nwalks, nsteps)) # 0 or 1
    steps = np.where(draws > 0, 1, -1)
    walks = steps.cumsum(1)
    walks_max = walks.max(axis=1)
    walks_min = walks.min(axis=1)
    first_crossing_time = (np.abs(walks) >= 10).argmax(axis=1)

    return walks_max, walks_min, first_crossing_time

In [27]:
walks_max, walks_min, first_crossing_time = random_walk_simulations(nsteps=1000, nwalks=5000)

In [30]:
print(walks_max)
print(walks_min)
print(first_crossing_time)

[28 29 41 ...  5  4 93]
[ -3 -17 -13 ... -43 -24  -4]
[ 49 103  69 ... 127  27  53]


In [28]:
print(np.quantile(walks_max, (0.05, 0.5, 0.95)))
print(np.quantile(walks_min, (0.05, 0.5, 0.95)))
print(np.quantile(first_crossing_time, (0.05, 0.5, 0.95)))

[ 2. 22. 62.]
[-60. -21.  -1.]
[ 19.  75. 269.]
